# Generated by Django 4.1.4 on 2022-12-14 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productvariantprice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductVariantPrice', to='product.product'),
        ),
    ]
